pub const ZERO_POOL: felt252 = 'LIMEN_ZERO_POOL';
pub const ZERO_TOKEN: felt252 = 'LIMEN_ZERO_TOKEN';
pub const ZERO_TARGET: felt252 = 'LIMEN_ZERO_TARGET';
pub const ZERO_THRESHOLD: felt252 = 'LIMEN_ZERO_THRESHOLD';
pub const ZERO_ACTION: felt252 = 'LIMEN_ZERO_ACTION';
pub const ZERO_ISSUER: felt252 = 'LIMEN_ZERO_ISSUER';
pub const ISSUER_NOT_CALLER: felt252 = 'LIMEN_ISSUER_NOT_CALLER';
pub const ALREADY_EXPIRED: felt252 = 'LIMEN_ALREADY_EXPIRED';
pub const CHALLENGE_EXISTS: felt252 = 'LIMEN_CHALLENGE_EXISTS';
pub const CHALLENGE_NOT_FOUND: felt252 = 'LIMEN_CHALLENGE_NOT_FOUND';
pub const CHALLENGE_CONSUMED: felt252 = 'LIMEN_CHALLENGE_CONSUMED';
pub const CHALLENGE_EXPIRED: felt252 = 'LIMEN_CHALLENGE_EXPIRED';
pub const WRONG_SUBJECT: felt252 = 'LIMEN_WRONG_SUBJECT';
pub const CALLER_NOT_POOL: felt252 = 'LIMEN_CALLER_NOT_POOL';
pub const ZERO_SUBJECT: felt252 = 'LIMEN_ZERO_SUBJECT';
pub const ZERO_NOTE_ID: felt252 = 'LIMEN_ZERO_NOTE_ID';
pub const BALANCE_OVERFLOW: felt252 = 'LIMEN_BALANCE_OVERFLOW';
pub const BALANCE_DECREASED: felt252 = 'LIMEN_BALANCE_DECREASED';
pub const BELOW_THRESHOLD: felt252 = 'LIMEN_BELOW_THRESHOLD';
pub const ABOVE_THRESHOLD: felt252 = 'LIMEN_ABOVE_THRESHOLD';
pub const APPROVE_FAILED: felt252 = 'LIMEN_APPROVE_FAILED';

// Target-application errors.
pub const CALLER_NOT_LIMEN: felt252 = 'GATE_CALLER_NOT_LIMEN';
pub const UNKNOWN_ACTION: felt252 = 'GATE_UNKNOWN_ACTION';
pub const WRONG_TOKEN: felt252 = 'GATE_WRONG_TOKEN';
pub const AMOUNT_TOO_LOW: felt252 = 'GATE_AMOUNT_TOO_LOW';
pub const ALLOCATION_EXISTS: felt252 = 'GATE_ALLOCATION_EXISTS';
