[package]
name = "limen_anonymizer"
version.workspace = true
edition.workspace = true
license.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[dependencies]
starknet.workspace = true
limen_shared = { path = "../limen_shared" }

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
limen_capital_gate = { path = "../limen_capital_gate" }

[features]
test_utils = []

[lib]

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true

[[test]]
name = "limen_anonymizer_unittest"
build-external-contracts = ["limen_capital_gate::capital_gate::CapitalGate"]
