//! Generated by scripts/generate-campaign.ts. Do not edit by hand.
//!
//! The deterministic adversarial campaign required by PRD §14: 100 cases over
//! 9 attack shapes, seeded from 0x4c494d454e so the same commit always
//! produces the same campaign.
//!
//! Each case is an independent test. A case that must be refused is a `should_panic`
//! on the exact error, so a case failing for the wrong reason is a failure, not a
//! pass. Regenerate with:
//!
//!     node --experimental-strip-types scripts/generate-campaign.ts

use super::campaign_harness::{
    run_below_threshold, run_direct_call, run_expired, run_malformed, run_replay, run_valid,
    run_wrong_subject, run_wrong_target, run_wrong_token,
};

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_001_valid() {
    run_valid(20, 0x1001, 2);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_002_valid() {
    run_valid(32, 0x1002, 1936);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_003_valid() {
    run_valid(51, 0x1003, 457);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_004_valid() {
    run_valid(43, 0x1004, 96);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_005_valid() {
    run_valid(27, 0x1005, 671);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_006_valid() {
    run_valid(39, 0x1006, 250);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_007_valid() {
    run_valid(24, 0x1007, 2829);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_008_valid() {
    run_valid(48, 0x1008, 1);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_009_valid() {
    run_valid(17, 0x1009, 51);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_010_valid() {
    run_valid(16, 0x100a, 1745);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_011_valid() {
    run_valid(31, 0x100b, 1238);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_012_valid() {
    run_valid(42, 0x100c, 1277);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_013_valid() {
    run_valid(36, 0x100d, 157);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_014_valid() {
    run_valid(34, 0x100e, 2841);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_015_valid() {
    run_valid(49, 0x100f, 716);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_016_valid() {
    run_valid(24, 0x1010, 2403);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_017_valid() {
    run_valid(33, 0x1011, 2302);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_018_valid() {
    run_valid(37, 0x1012, 1346);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_019_valid() {
    run_valid(31, 0x1013, 2880);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_020_valid() {
    run_valid(45, 0x1014, 1237);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_021_valid() {
    run_valid(40, 0x1015, 2285);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_022_valid() {
    run_valid(26, 0x1016, 2173);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_023_valid() {
    run_valid(42, 0x1017, 2654);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_024_valid() {
    run_valid(38, 0x1018, 2442);
}

/// Correct subject, token, target, action and exact threshold. Must clear and register the allocation.
#[test]
fn case_025_valid() {
    run_valid(59, 0x1019, 1969);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_026_below_threshold() {
    run_below_threshold(16, 10, 0x101a);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_027_below_threshold() {
    run_below_threshold(41, 23, 0x101b);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_028_below_threshold() {
    run_below_threshold(40, 39, 0x101c);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_029_below_threshold() {
    run_below_threshold(36, 25, 0x101d);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_030_below_threshold() {
    run_below_threshold(51, 46, 0x101e);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_031_below_threshold() {
    run_below_threshold(45, 17, 0x101f);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_032_below_threshold() {
    run_below_threshold(57, 38, 0x1020);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_033_below_threshold() {
    run_below_threshold(51, 45, 0x1021);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_034_below_threshold() {
    run_below_threshold(43, 10, 0x1022);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_035_below_threshold() {
    run_below_threshold(58, 48, 0x1023);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_036_below_threshold() {
    run_below_threshold(24, 7, 0x1024);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_037_below_threshold() {
    run_below_threshold(11, 1, 0x1025);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_038_below_threshold() {
    run_below_threshold(52, 22, 0x1026);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_039_below_threshold() {
    run_below_threshold(48, 34, 0x1027);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_040_below_threshold() {
    run_below_threshold(57, 26, 0x1028);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_041_below_threshold() {
    run_below_threshold(52, 21, 0x1029);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_042_below_threshold() {
    run_below_threshold(15, 2, 0x102a);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_043_below_threshold() {
    run_below_threshold(20, 1, 0x102b);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_044_below_threshold() {
    run_below_threshold(50, 15, 0x102c);
}

/// Less than the threshold reaches the anonymizer. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_BELOW_THRESHOLD')]
fn case_045_below_threshold() {
    run_below_threshold(41, 14, 0x102d);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_046_expired() {
    run_expired(54, 0x102e, 4586);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_047_expired() {
    run_expired(47, 0x102f, 4583);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_048_expired() {
    run_expired(15, 0x1030, 3771);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_049_expired() {
    run_expired(54, 0x1031, 4504);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_050_expired() {
    run_expired(21, 0x1032, 4240);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_051_expired() {
    run_expired(23, 0x1033, 3661);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_052_expired() {
    run_expired(18, 0x1034, 3706);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_053_expired() {
    run_expired(39, 0x1035, 3907);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_054_expired() {
    run_expired(52, 0x1036, 3619);
}

/// Cleared after the challenge's expiry second. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_EXPIRED')]
fn case_055_expired() {
    run_expired(39, 0x1037, 3809);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_056_replay() {
    run_replay(55, 0x1038);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_057_replay() {
    run_replay(49, 0x1039);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_058_replay() {
    run_replay(56, 0x103a);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_059_replay() {
    run_replay(13, 0x103b);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_060_replay() {
    run_replay(40, 0x103c);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_061_replay() {
    run_replay(52, 0x103d);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_062_replay() {
    run_replay(55, 0x103e);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_063_replay() {
    run_replay(51, 0x103f);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_064_replay() {
    run_replay(47, 0x1040);
}

/// A challenge that already cleared is presented again. Must not clear twice.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_CONSUMED')]
fn case_065_replay() {
    run_replay(27, 0x1041);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_066_wrong_target() {
    run_wrong_target(57, 0x1042);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_067_wrong_target() {
    run_wrong_target(41, 0x1043);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_068_wrong_target() {
    run_wrong_target(51, 0x1044);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_069_wrong_target() {
    run_wrong_target(50, 0x1045);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_070_wrong_target() {
    run_wrong_target(16, 0x1046);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_071_wrong_target() {
    run_wrong_target(21, 0x1047);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_072_wrong_target() {
    run_wrong_target(27, 0x1048);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_073_wrong_target() {
    run_wrong_target(24, 0x1049);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_074_wrong_target() {
    run_wrong_target(44, 0x104a);
}

/// The challenge names a gate bound to a different Limen deployment. That gate must refuse.
#[test]
#[should_panic(expected: 'GATE_CALLER_NOT_LIMEN')]
fn case_075_wrong_target() {
    run_wrong_target(34, 0x104b);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_076_wrong_token() {
    run_wrong_token(59, 0x104c);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_077_wrong_token() {
    run_wrong_token(35, 0x104d);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_078_wrong_token() {
    run_wrong_token(17, 0x104e);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_079_wrong_token() {
    run_wrong_token(47, 0x104f);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_080_wrong_token() {
    run_wrong_token(45, 0x1050);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_081_wrong_token() {
    run_wrong_token(36, 0x1051);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_082_wrong_token() {
    run_wrong_token(11, 0x1052);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_083_wrong_token() {
    run_wrong_token(43, 0x1053);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_084_wrong_token() {
    run_wrong_token(42, 0x1054);
}

/// The challenge names a token the gate does not accept. The gate must refuse.
#[test]
#[should_panic(expected: 'GATE_WRONG_TOKEN')]
fn case_085_wrong_token() {
    run_wrong_token(59, 0x1055);
}

/// A subject the challenge is not bound to. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_WRONG_SUBJECT')]
fn case_086_wrong_subject() {
    run_wrong_subject(45, 0x1056);
}

/// A subject the challenge is not bound to. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_WRONG_SUBJECT')]
fn case_087_wrong_subject() {
    run_wrong_subject(45, 0x1057);
}

/// A subject the challenge is not bound to. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_WRONG_SUBJECT')]
fn case_088_wrong_subject() {
    run_wrong_subject(47, 0x1058);
}

/// A subject the challenge is not bound to. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_WRONG_SUBJECT')]
fn case_089_wrong_subject() {
    run_wrong_subject(31, 0x1059);
}

/// A subject the challenge is not bound to. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_WRONG_SUBJECT')]
fn case_090_wrong_subject() {
    run_wrong_subject(59, 0x105a);
}

/// A challenge identifier that was never created. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_NOT_FOUND')]
fn case_091_malformed() {
    run_malformed(0x105b);
}

/// A challenge identifier that was never created. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_NOT_FOUND')]
fn case_092_malformed() {
    run_malformed(0x105c);
}

/// A challenge identifier that was never created. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_NOT_FOUND')]
fn case_093_malformed() {
    run_malformed(0x105d);
}

/// A challenge identifier that was never created. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_NOT_FOUND')]
fn case_094_malformed() {
    run_malformed(0x105e);
}

/// A challenge identifier that was never created. Must not clear.
#[test]
#[should_panic(expected: 'LIMEN_CHALLENGE_NOT_FOUND')]
fn case_095_malformed() {
    run_malformed(0x105f);
}

/// The anonymizer is called directly rather than through the pool. Must be refused.
#[test]
#[should_panic(expected: 'LIMEN_CALLER_NOT_POOL')]
fn case_096_direct_call() {
    run_direct_call(27, 0x1060);
}

/// The anonymizer is called directly rather than through the pool. Must be refused.
#[test]
#[should_panic(expected: 'LIMEN_CALLER_NOT_POOL')]
fn case_097_direct_call() {
    run_direct_call(44, 0x1061);
}

/// The anonymizer is called directly rather than through the pool. Must be refused.
#[test]
#[should_panic(expected: 'LIMEN_CALLER_NOT_POOL')]
fn case_098_direct_call() {
    run_direct_call(43, 0x1062);
}

/// The anonymizer is called directly rather than through the pool. Must be refused.
#[test]
#[should_panic(expected: 'LIMEN_CALLER_NOT_POOL')]
fn case_099_direct_call() {
    run_direct_call(23, 0x1063);
}

/// The anonymizer is called directly rather than through the pool. Must be refused.
#[test]
#[should_panic(expected: 'LIMEN_CALLER_NOT_POOL')]
fn case_100_direct_call() {
    run_direct_call(31, 0x1064);
}
